### ISSUE TITLE
modal_change object crash on "steps" message received

### ISSUE THREAD

**Issue by vjmanzo** [EAMIRorg/Modal_Object_Library#1]
### Issue
The modal_change object crashes when it receives a message of "steps" in the right inlet if it, at load/instantiation, it has not received
- a tonic (at the left inlet) via loadbang/loadmess
- a mode (at the right inlet) via loadbang/loadmess

**Work on this solution to this issue on the debugging branch of the repo.** 

### Issue in Max
The object has been working since Max 5, works fine in Max 7 and earlier and the only thing change to our project when we recompiled in XCode is the max-sdk version (8.0.3). The previous version of modal_change compiled with the max-sdk version 6 produces the same crash in Max 8, but not in Max 7. 

I have reduced the problem to two test patches contained in the repo at _max-sdk-8.0.3⁩ ▸ ⁨externals⁩,_ which contains some descriptive narrative about how to avoid the crash and how to trigger it. 

**How to Test:**
open _test with loadbangs.maxpat_ and you can send "pattern" messages to the right inlet to change the mode without Max crashing, but when you open _test without loadbangs.maxpat_, Max will crash when you send "pattern" messages. 

As you can see in the patch, the functionality we programmed into the object does still work, but the object now needs to be instantiated with default values (tonic and mode via first and second inlets) via loadbang/loadmess in order to use the whole/half steps "pattern" message box or else it crashes.

**In XCode:**
Possibly related, the XCode project has some issues referencing the cycling74 support folder (located in the repo at ⁨_max-sdk-8.0.3⁩ ▸ ⁨source⁩ ▸ ⁨c74support⁩_ ) and, as such, paths to the #include header files (in _modal_change.cpp_) needed to be hardcoded in order for the object to compile. 
**Note:** Avoid doing a "Clean Build Folder" as this will wipe out the two _.maxpat_ test files. 

### Issue in XCode
Feedback from Cycling 74:<br>
The crash seems to happen on this std::equal() call on line 499 of the main modal_change object code.
<img width="640" alt="1" src="https://user-images.githubusercontent.com/3967529/110248728-989d1d00-7f40-11eb-837a-773e962e2abc.png">

This is the debugging session when going through the working patch (which has been pre-initialized with loadbang). This does not crash. Notice that the t_mode_map is of length 35 and this first element is "aeolian".

I then went through a case without the pre-initialization:
<img width="640" alt="2" src="https://user-images.githubusercontent.com/3967529/110248738-a3f04880-7f40-11eb-8edf-ff281e49807f.png">
I noticed that the first element of the t_mode_map is now "=====" and the length is 36. This situation crashes.

### Boost
The modal_change object originally required Boost 1.43, then Boost 1.57 and, presumably, the object will now work with Boost 1.76.0
➝install Boost with Homebrew https://formulae.brew.sh/formula/boost

**Comment by ghost** [comment]
## PROPOSED FIX
!!!Only tested with Max8!!!
The first element of g_mode_map (map<string, vector\<int>>) after initialization is <"=====", emptyVector>

* check for empty vector before comparing with std::equal.
 
``` 
    bool modal_change_determine_modename(vector<int> *intervals, string *mode_str) {
        t_mode_map::iterator it;
       
       for(it = g_mode_map.begin(); it != g_mode_map.end(); it++) {
           // if vector is not empty, then check equality
            if(!it->second.empty() && std::equal(intervals->begin(), intervals->end(), it->second.begin())) {
            mode_str->assign(it->first);
            break;
        }
    }
    return(it != g_mode_map.end());
} 
```

Questions:
Does entry <"=====", emptyVector> need to be in g_mode_map?

**Comment by vjmanzo** [comment]
This resolved the issue. Nice going, Jake!
